### PR TITLE
Fixed directory mathias -> mathiasg

### PR DESCRIPTION
**Pull request by sitek**
updated for openmind

### CODE REVIEW

**Comment by sitek** [comment]
could you also make this file readable? or copy it somewhere I can access it?

**Comment by mgxd** [comment]
@sitek that path is hardcoded for my ubuntu setup - if you wanna run on /om comment out line 292 and uncomment 291

**Comment by sitek** [comment]
Gah! Thought I was being helpful. Will close the PR. thanks!

**Comment by sitek** [comment]
Actually, the file is still unreadable (permissions) - could you change permissions or copy it somewhere?

**Comment by mgxd** [comment]
hm that's weird - you should be able to download the file [here](https://www.dropbox.com/s/avlpaav34bzs6u9/rfMRI_REST1_LR_Atlas.dtseries.nii?dl=0)

**Pull request closed without merging**
